# SSH key pair generated by Terraform (pure-Terraform, no manual step). The private key is
# written to a local file (0600) and also lives in local state — both are gitignored. Acceptable
# for a 4-day POC; documented in DESIGN.md. Destroy removes the AWS key pair and the local file.

resource "tls_private_key" "node" {
  algorithm = "ED25519"
}

resource "aws_key_pair" "node" {
  key_name   = "${local.name}-key"
  public_key = tls_private_key.node.public_key_openssh
  tags       = { Name = "${local.name}-key" }
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.node.private_key_openssh
  filename        = "${path.module}/${local.name}-key.pem"
  file_permission = "0600"
}
